name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  checks:
    # Ignore the heap-code bot commits
    if: ${{ github.actor != vars.HC_BOT }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test:coverage -- --ci

      - name: Comments coverage
        run: npm run compodoc:coverage
